### ISSUE TITLE
package.lock contains references to localhost

### ISSUE THREAD

**Issue by tcoopman** [bmomberger-bitovi/web-components-example#2]
So, it's not possible to clone and install this package.

**Comment by bmomberger-bitovi** [comment]
It is possible.  You need to set up https://verdaccio.org/ to run locally (I recommend using a Docker container) and then you can deploy to your local artifact repo.

**Comment by bmomberger-bitovi** [comment]
Package-lock is not necessary for developers, only for CI and production, so feel free to delete it when it causes errors and behavoir you don't like.  That said, there is also an .npmrc in this repo that points to localhost for NPM, which is necessary for my current workflow around this repo.  You should also remove that if you want to build and run this project.
